# this file is used to configure nginx on our web server( YAML file)

---
# which host do we need to install nginx in
- hosts: webservers
  gather_facts: true



# what facts do we want to see while installing
  



# do we need admin access? YES
  become: true

# what task do we want to perform in this yml file
  tasks:
  - name: Install Nginx in Web Agent Node
    apt: pkg=nginx state=present
    become_user: root
  - name: Ansible copy file to remote server
    copy:
      src: /etc/ansible/default
      dest: /etc/nginx/sites-available/default
# what is the end goal for this task
# nginx status running

  - name: restart nginx
    service: name=nginx state=restarted


  
 # - name: restart nginx
 #   service: name=nginx state=restarted
